//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.28 at 06:41:14 PM EST 
//


package logger.xml.defInstance;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "replace"
})
@XmlRootElement(name = "conversion")
public class Conversion {

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String expr;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String format;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String storagetype;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String units;
    @XmlAttribute(name = "gauge_min")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String gaugeMin;
    @XmlAttribute(name = "gauge_max")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String gaugeMax;
    @XmlAttribute(name = "gauge_step")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String gaugeStep;
    protected List<Replace> replace;

    /**
     * Gets the value of the expr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpr() {
        return expr;
    }

    /**
     * Sets the value of the expr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpr(String value) {
        this.expr = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the storagetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoragetype() {
        return storagetype;
    }

    /**
     * Sets the value of the storagetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoragetype(String value) {
        this.storagetype = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnits(String value) {
        this.units = value;
    }

    /**
     * Gets the value of the gaugeMin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGaugeMin() {
        return gaugeMin;
    }

    /**
     * Sets the value of the gaugeMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGaugeMin(String value) {
        this.gaugeMin = value;
    }

    /**
     * Gets the value of the gaugeMax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGaugeMax() {
        return gaugeMax;
    }

    /**
     * Sets the value of the gaugeMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGaugeMax(String value) {
        this.gaugeMax = value;
    }

    /**
     * Gets the value of the gaugeStep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGaugeStep() {
        return gaugeStep;
    }

    /**
     * Sets the value of the gaugeStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGaugeStep(String value) {
        this.gaugeStep = value;
    }

    /**
     * Gets the value of the replace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the replace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReplace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Replace }
     * 
     * 
     */
    public List<Replace> getReplace() {
        if (replace == null) {
            replace = new ArrayList<Replace>();
        }
        return this.replace;
    }

}
