//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.28 at 06:41:14 PM EST 
//


package logger.xml.defInstance;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addressOrConversionsOrDepends"
})
@XmlRootElement(name = "parameter")
public class Parameter {

    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ecubit;
    @XmlAttribute
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String ecubyteindex;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String desc;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlElements({
        @XmlElement(name = "address", required = true, type = Address.class),
        @XmlElement(name = "conversions", required = true, type = Conversions.class),
        @XmlElement(name = "depends", required = true, type = Depends.class)
    })
    protected List<Object> addressOrConversionsOrDepends;

    /**
     * Gets the value of the ecubit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcubit() {
        return ecubit;
    }

    /**
     * Sets the value of the ecubit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcubit(String value) {
        this.ecubit = value;
    }

    /**
     * Gets the value of the ecubyteindex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcubyteindex() {
        return ecubyteindex;
    }

    /**
     * Sets the value of the ecubyteindex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcubyteindex(String value) {
        this.ecubyteindex = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the addressOrConversionsOrDepends property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addressOrConversionsOrDepends property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddressOrConversionsOrDepends().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Address }
     * {@link Conversions }
     * {@link Depends }
     * 
     * 
     */
    public List<Object> getAddressOrConversionsOrDepends() {
        if (addressOrConversionsOrDepends == null) {
            addressOrConversionsOrDepends = new ArrayList<Object>();
        }
        return this.addressOrConversionsOrDepends;
    }

}
