//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.28 at 06:41:14 PM EST 
//


package logger.xml.defInstance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parameters",
    "switches",
    "ecuparams"
})
@XmlRootElement(name = "protocol")
public class Protocol {

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String baud;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String databits;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String stopbits;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String parity;
    @XmlAttribute(name = "connect_timeout", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String connectTimeout;
    @XmlAttribute(name = "send_timeout", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String sendTimeout;
    protected Parameters parameters;
    protected Switches switches;
    protected Ecuparams ecuparams;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the baud property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaud() {
        return baud;
    }

    /**
     * Sets the value of the baud property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaud(String value) {
        this.baud = value;
    }

    /**
     * Gets the value of the databits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabits() {
        return databits;
    }

    /**
     * Sets the value of the databits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabits(String value) {
        this.databits = value;
    }

    /**
     * Gets the value of the stopbits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopbits() {
        return stopbits;
    }

    /**
     * Sets the value of the stopbits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopbits(String value) {
        this.stopbits = value;
    }

    /**
     * Gets the value of the parity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParity() {
        return parity;
    }

    /**
     * Sets the value of the parity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParity(String value) {
        this.parity = value;
    }

    /**
     * Gets the value of the connectTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectTimeout() {
        return connectTimeout;
    }

    /**
     * Sets the value of the connectTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectTimeout(String value) {
        this.connectTimeout = value;
    }

    /**
     * Gets the value of the sendTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendTimeout() {
        return sendTimeout;
    }

    /**
     * Sets the value of the sendTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendTimeout(String value) {
        this.sendTimeout = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link Parameters }
     *     
     */
    public Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parameters }
     *     
     */
    public void setParameters(Parameters value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the switches property.
     * 
     * @return
     *     possible object is
     *     {@link Switches }
     *     
     */
    public Switches getSwitches() {
        return switches;
    }

    /**
     * Sets the value of the switches property.
     * 
     * @param value
     *     allowed object is
     *     {@link Switches }
     *     
     */
    public void setSwitches(Switches value) {
        this.switches = value;
    }

    /**
     * Gets the value of the ecuparams property.
     * 
     * @return
     *     possible object is
     *     {@link Ecuparams }
     *     
     */
    public Ecuparams getEcuparams() {
        return ecuparams;
    }

    /**
     * Sets the value of the ecuparams property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ecuparams }
     *     
     */
    public void setEcuparams(Ecuparams value) {
        this.ecuparams = value;
    }

}
